# Generated by Django 2.2.9 on 2022-05-19 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20220519_0010'),
        ('posts', '0005_auto_20220518_2229'),
    ]

    operations = [
    ]
