# Generated by Django 2.2.16 on 2022-07-05 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20220705_1701'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': ('Пост',), 'verbose_name_plural': 'Посты'},
        ),
    ]
