# Generated by Django 2.2.16 on 2022-07-09 09:27

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_auto_20220709_1223'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='follow_himself',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(('author', django.db.models.expressions.F('user')), ('user', django.db.models.expressions.F('author'))), name='follow_himself'),
        ),
    ]
