# Generated by Django 2.2.16 on 2022-07-09 09:30

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_auto_20220709_1227'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='follow_himself',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, author=django.db.models.expressions.F('user')), name='follow_himself'),
        ),
    ]
